In [108]:
import pandas as pd

from submission_utils import test_submission

In [109]:
subm = pd.read_csv("prueba_economistnet3.csv", parse_dates=True, index_col="date")

In [110]:
submission_muestra = pd.read_csv("submission/submission.csv", parse_dates=True, index_col="eod_ts")

In [111]:
subm.head()

,ACY,BGN,BSX,EEY,FIR,HEO,HQU,JTL,LEN,LWK,OJG,REU,SEH,UEI,UYZ,VRT,YEC,ZXW
date,,,,,,,,,,,,,,,,,,
2020-08-18,0.0,0.200,0.2,0.030,0.012,0.012,0.0,0.189,0.038,0.071,0.050,0.0,0.0,0.093,0.053,0.0,0.052,0.0
2020-08-19,0.0,0.200,0.2,0.034,0.021,0.011,0.0,0.189,0.029,0.074,0.041,0.0,0.0,0.092,0.053,0.0,0.056,0.0
2020-08-20,0.0,0.201,0.2,0.036,0.023,0.011,0.0,0.187,0.027,0.076,0.038,0.0,0.0,0.090,0.056,0.0,0.055,0.0
2020-08-21,0.0,0.201,0.2,0.037,0.019,0.005,0.0,0.187,0.027,0.075,0.037,0.0,0.0,0.094,0.061,0.0,0.057,0.0
2020-08-24,0.0,0.201,0.2,0.037,0.010,0.000,0.0,0.186,0.031,0.074,0.038,0.0,0.0,0.102,0.065,0.0,0.056,0.0

In [112]:
submission_muestra.shape

(2229, 18)

In [113]:
subm.resample("H").aggregate("mean")

,ACY,BGN,BSX,EEY,FIR,HEO,HQU,JTL,LEN,LWK,OJG,REU,SEH,UEI,UYZ,VRT,YEC,ZXW
date,,,,,,,,,,,,,,,,,,
2020-08-18 00:00:00,0.0,0.2,0.2,0.03,0.012,0.012,0.0,0.189,0.038,0.071,0.050,0.000,0.0,0.093,0.053,0.000,0.052,0.0
2020-08-18 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-08-18 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-08-18 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-08-18 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-23 20:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-12-23 21:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-12-23 22:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-12-23 23:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-12-24 00:00:00,0.0,0.2,0.2,0.06,0.047,0.014,0.0,0.172,0.000,0.049,0.067,0.006,0.0,0.018,0.093,0.019,0.055,0.0

In [114]:
ref_index =submission_muestra.index

In [115]:
df_index = pd.DataFrame({"date": ref_index}).set_index("date")

In [116]:
subm.index

DatetimeIndex(['2020-08-18', '2020-08-19', '2020-08-20', '2020-08-21',
               '2020-08-24', '2020-08-25', '2020-08-26', '2020-08-27',
               '2020-08-28', '2020-08-31', '2020-09-01', '2020-09-02',
               '2020-09-03', '2020-09-04', '2020-09-07', '2020-09-08',
               '2020-09-09', '2020-09-10', '2020-09-11', '2020-09-14',
               '2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
               '2020-09-21', '2020-09-22', '2020-09-23', '2020-09-24',
               '2020-09-25', '2020-09-28', '2020-09-29', '2020-09-30',
               '2020-10-01', '2020-10-02', '2020-10-05', '2020-10-06',
               '2020-10-07', '2020-10-08', '2020-10-09', '2020-10-12',
               '2020-10-13', '2020-10-14', '2020-10-15', '2020-10-16',
               '2020-10-19', '2020-10-20', '2020-10-21', '2020-10-22',
               '2020-10-23', '2020-10-26', '2020-10-27', '2020-10-28',
               '2020-10-29', '2020-10-30', '2020-11-02', '2020-11-03',
               '2020-11-04', '2020-11-05', '2020-11-06', '2020-11-09',
               '2020-11-10', '2020-11-11', '2020-11-12', '2020-11-13',
               '2020-11-16', '2020-11-17', '2020-11-18', '2020-11-19',
               '2020-11-20', '2020-11-23', '2020-11-24', '2020-11-25',
               '2020-11-26', '2020-11-27', '2020-11-30', '2020-12-01',
               '2020-12-02', '2020-12-03', '2020-12-04', '2020-12-07',
               '2020-12-08', '2020-12-09', '2020-12-10', '2020-12-11',
               '2020-12-14', '2020-12-15', '2020-12-16', '2020-12-17',
               '2020-12-18', '2020-12-21', '2020-12-22', '2020-12-23',
               '2020-12-24'],
              dtype='datetime64[ns]', name='date', freq=None)

In [117]:
final_submission = pd.merge(subm.resample("H").aggregate("mean").ffill(), df_index, right_index=True, left_index=True, how="right").ffill()

In [118]:
final_submission.index = final_submission.index.rename("eod_ts")

In [119]:
cols_ = [col.replace("allo_", "") for col in submission_muestra.columns]

In [120]:
final_submission = final_submission.reindex(columns = cols_ )

In [121]:
final_submission = final_submission[cols_]

In [122]:
final_submission.head()

,REU,VRT,EEY,JTL,SEH,BSX,OJG,UEI,HQU,ZXW,LEN,YEC,UYZ,LWK,ACY,HEO,FIR,BGN
eod_ts,,,,,,,,,,,,,,,,,,
2020-08-18 00:00:00,0.0,0.0,0.03,0.189,0.0,0.2,0.05,0.093,0.0,0.0,0.038,0.052,0.053,0.071,0.0,0.012,0.012,0.2
2020-08-18 01:00:00,0.0,0.0,0.03,0.189,0.0,0.2,0.05,0.093,0.0,0.0,0.038,0.052,0.053,0.071,0.0,0.012,0.012,0.2
2020-08-18 02:00:00,0.0,0.0,0.03,0.189,0.0,0.2,0.05,0.093,0.0,0.0,0.038,0.052,0.053,0.071,0.0,0.012,0.012,0.2
2020-08-18 03:00:00,0.0,0.0,0.03,0.189,0.0,0.2,0.05,0.093,0.0,0.0,0.038,0.052,0.053,0.071,0.0,0.012,0.012,0.2
2020-08-18 04:00:00,0.0,0.0,0.03,0.189,0.0,0.2,0.05,0.093,0.0,0.0,0.038,0.052,0.053,0.071,0.0,0.012,0.012,0.2

In [67]:
df = final_submission.copy()

In [68]:
df.loc[:,:] = df.loc[:,:].div(df.sum(axis=1), axis=0)

In [71]:
all(df.sum(axis=1) == 1)

False

In [66]:
#final_submission.iloc[:, 1:] / final_submission.iloc[:, 1:].sum(axis=1)

In [54]:
final_submission.iloc[:, :] = final_submission. / final_submission.sum(axis=1)

In [55]:
final_submission

,2020-08-18 00:00:00,2020-08-18 01:00:00,2020-08-18 02:00:00,2020-08-18 03:00:00,2020-08-18 04:00:00,2020-08-18 05:00:00,2020-08-18 06:00:00,2020-08-18 07:00:00,2020-08-18 08:00:00,2020-08-18 09:00:00,...,LEN,LWK,OJG,REU,SEH,UEI,UYZ,VRT,YEC,ZXW
eod_ts,,,,,,,,,,,,,,,,,,,,,
2020-08-18 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-08-18 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-08-18 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-08-18 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-08-18 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-24 17:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-12-24 18:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-12-24 19:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-12-24 20:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-12-24 21:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [123]:
final_submission.columns = [f"allo_{col}" for col in final_submission.columns]

In [125]:
final_submission.sum(axis=1)

eod_ts
2020-08-18 00:00:00    1.0
2020-08-18 01:00:00    1.0
2020-08-18 02:00:00    1.0
2020-08-18 03:00:00    1.0
2020-08-18 04:00:00    1.0
                      ...
2020-12-24 17:00:00    1.0
2020-12-24 18:00:00    1.0
2020-12-24 19:00:00    1.0
2020-12-24 20:00:00    1.0
2020-12-24 21:00:00    1.0
Length: 2229, dtype: float64

In [ ]:
subm2 = final_submission.div(final

In [126]:
subm2 = final_submission.div(final_submission.sum(axis=1), axis=0)

In [128]:
test_submission(subm2)

In [129]:
subm2.to_csv("submission_2202_3.csv", header=True, index=True)